### PR TITLE
Forced formatoptions to have at least 'tc'

### PR DESCRIPTION
**Pull request by jgkamat**
I also added a g:EditorConfig_preserve_formatoptions to keep the old behavior, if anyone wanted that.

Let me know if I'm making any mistakes, this is my first time doing anything serious with vimscript.
Thanks!

### CODE REVIEW

**Comment by xuhdev** [comment]
Can you add modify the line in the doc to: ... to be modified when max_line_length is set?

**Comment by jgkamat** [comment]
Just fixed that, let me know if you see anything else wrong!

**Comment by xuhdev** [comment]
Thanks! Can you merge these 3 commits into 1 commit? They do not look like separated steps of work

**Comment by jgkamat** [comment]
Sure thing, I just did that, anything else?

**Comment by xuhdev** [comment]
Looks good now. Thanks!

**Pull request merged**
