### PR TITLE
Add support `indent_style = none`

### PR DESCRIPTION
**Pull request by nzmosh**
Related issue: https://github.com/editorconfig/editorconfig/issues/214

I assume there are more appropriate ways fot fixing this but I'm not an expert for vim plugin :/

### CODE REVIEW

**Comment by xuhdev** [comment]
Thanks for your fix. Unfortunately, it may probably not work: `smartindent`, `cindent` options may still have effects. We don't have a consensus on `none` or `disable` or any other words to use yet (it has to be cross-editors), so I cannot accept this PR at this moment. I'll leave this PR open until we have some news.

**Comment by mgaoshima** [comment]
Thanks for your comment!
I just wait for EditorConfig updates :+1:

**Comment by xuhdev** [comment]
I looked at this again, and it doesn't seem to fit in the overall framework of EditorConfig. All editor plugins ignore unknown property values so we can achieve best future compatibility and plugins' extensions. (see `Create a Plugin` section on the [homepage](https://editorconfig.org/)) This seems to break the rules by enforcing a rule on an unknown property. Now we have a reserved keyword `unset`, which simply asks editor plugins to ignore it. Thoughts?

**Comment by cxw42** [comment]
@nzmosh I'm guessing you've found another option by now :) .  I am going to close this PR as inactive, but feel free to bump the discussion in editorconfig/editorconfig#214 if you still want this feature.  Thanks!

**Pull request closed without merging**
