### PR TITLE
Fix the vim scripts to be reloadable

### PR DESCRIPTION
**Pull request by LucHermitte**
... without exiting vim

### CODE REVIEW

**Comment by LucHermitte** [comment]
Hi,
Sorry for the delay in my answer. I wanted to provide a little demo for you to see the difference, but I'm on other subjects right now.

When used, `abort` simplifies the error messages displayed by Vim. It usually starts by removing all the "E???: missing :endif/:endwhile" errors.

Of course editorconfig hooks aren't supposed to produce errors, alas hooks may be bugged while they are being developed. By appending the `abort` these unexpected error messages will be simplified.

On the subject, see the extremely short recommendation from google style guide for Vim: https://google.github.io/styleguide/vimscriptguide.xml#Functions

**Comment by LucHermitte** [comment]
It's my mistake, the PR actually introduces two unrelated things

- it makes the script reloadable (with the bang character: `!`)
- it improves error messages  (with `abort` annotation)

It's my fault for mixing the two in only one PR as they both change function signatures.

Don't worry about the late response.

**Comment by xuhdev** [comment]
@LucHermitte I'm good with the reloadable part, but I'm very worried about the `abort` keyword. Why should we ignore error messages? This may introduce a lot of hidden issues that users cannot recognize.

**Comment by yous** [comment]
Using `abort` is not ignoring error messages, it makes functions to abort immediately when an error occurs. See `:help except-compat`:

```
                                                        except-compat
The exception handling concept requires that the command sequence causing the
exception is aborted immediately and control is transferred to finally clauses
and/or a catch clause.

In the Vim script language there are cases where scripts and functions
continue after an error: in functions without the "abort" flag or in a command
after ":silent!", control flow goes to the following line, and outside
functions, control flow goes to the line following the outermost ":endwhile"
or ":endif".  On the other hand, errors should be catchable as exceptions
(thus, requiring the immediate abortion).

This problem has been solved by converting errors to exceptions and using
immediate abortion (if not suppressed by ":silent!") only when a try
conditional is active.  This is no restriction since an (error) exception can
be caught only from an active try conditional.  If you want an immediate
termination without catching the error, just use a try conditional without
catch clause.  (You can cause cleanup code being executed before termination
by specifying a finally clause.)
```

For example, when `:unmap` is called with a mapping that doesn't exist, an error E31 occurs.
``` vim
function! s:a()
  call s:b()
  unmap NoMapA
endfunction

function! s:b()
  call s:c()
  unmap NoMapB
endfunction

function! s:c()
  unmap NoMapC
endfunction

call s:a()
```
Then the error messages are:
```
Error detected while processing function <SNR>85_a[1]..<SNR>85_b[1]..<SNR>85_c:
line    1:
E31: No such mapping
Error detected while processing function <SNR>85_a[1]..<SNR>85_b:
line    2:
E31: No such mapping
Error detected while processing function <SNR>85_a:
line    2:
E31: No such mapping
```

But with `abort`, function will stop executing right after an error occurs.
``` vim
function! s:a() abort
  call s:b()
  unmap NoMapA
endfunction

function! s:b() abort
  call s:c()
  unmap NoMapB
endfunction

function s:c() abort
  unmap NoMapC
endfunction

call s:a()
```

The error messages are less because it stops executing.
```
Error detected while processing function <SNR>85_a[1]..<SNR>85_b[1]..<SNR>85_c:
line    1:
E31: No such mapping
```

**Pull request merged**
