### PR TITLE
Utilize autoload

### PR DESCRIPTION
**Pull request by k-takata**
Move most part from `plugin/` to `autoload/`.
Also delay the initialization until it is really needed. (No need to initialize if no `.editorconfig` files are found.)
This reduces the startup time about 50 msec in my environment even if the files are cached by the OS.

### CODE REVIEW

**Comment by k-takata** [comment]
Git subtree doesn't hold a local directory name unlike submodule.
So next time you pull `editorconfig-core-py`, you just need to specify the new directory with `--prefix=`.
E.g.

```
git subtree pull --prefix=autoload/editorconfig-core-py https://github.com/editorconfig/editorconfig-core-py.git master
```

(confirmed)

**Comment by k-takata** [comment]
mkzip.sh has been updated.

**Comment by k-takata** [comment]
Fixed that .editorconfig files in parent directories were not searched.
I think this is ready to be merged.

**Comment by k-takata** [comment]
Fixed conflict caused by merging #78.
This also includes equivalent fix to #79.

**Comment by xuhdev** [comment]
Seems still conflicting...

**Comment by k-takata** [comment]
Fixed conflict against #81.

**Comment by xuhdev** [comment]
Still conflicting..

**Comment by xuhdev** [comment]
Actually I'm kind of hesitate to make the change. People who upgrade will face this issue: they need to be aware to upgrade by hand. Do you happen to know a way to automatically change the subtree directory when a new pull occurs?

**Comment by k-takata** [comment]
Finally I found that utilizing autoload was not necessary.
The most important point for decreasing startup time of Vim is delaying the load of python.

At first, I used autoload in [this commit](https://github.com/editorconfig/editorconfig-vim/pull/73/commits/b70c94bf759dfda3cd55198d411a1487363b39e8). It actually delayed loading of python, but I added [another commit](https://github.com/editorconfig/editorconfig-vim/pull/73/commits/16d9f384e5244816a11c803fc166edee40dc49b1) on top of it. As the result, autoload was not needed after this.

I withdraw this PR and create a new PR.

**Pull request closed without merging**
