### PR TITLE
Respect modifiable flag when trimming whitespace

### PR DESCRIPTION
**Pull request by op**
Refs #83.

### CODE REVIEW

**Comment by xuhdev** [comment]
Thanks!

**Comment by b0o** [comment]
Hey! Thanks for this, I've been having the same issue for a while now and it's been bugging me.

I checked out your branch and it did make the error go away, but now I'm getting two new splits popping up:
screen shot 2017-04-18 at 10 01 03 am

Here's what it looks like with the old master before your commit (26781c577da740786a4d1723ddaddfef79701e32):
screen shot 2017-04-18 at 10 10 00 am

I'm not sure if this is a problem with `vim-go` or `editorconfig-vim` or if this is the intended behavior?

**Comment by xuhdev** [comment]
@b0o This looks like some go lint program shows the error. It's unlikely to be related to `editorconfig-vim`. You can check whether it is caused by `vim-go` or `syntax_checker` or something similar.

**Comment by b0o** [comment]
@xuhdev Yeah, sorry. The panes are both from `vim-go`, one of them is GoLint and the other is GoMetaLinter.

I think what was happening was that prior to @op's fix, the error was causing only GoLint to run and not GoMetaLinter, so when it was fixed I was confused because I was so used to the old behavior. 😝

**Pull request merged**
