### PR TITLE
Uses a range(&textwidth,&columns) instead of a single column on vim.

### PR DESCRIPTION
**Pull request by arteymix**
It is much more elegant than a single column being highlighted.

### CODE REVIEW

**Comment by arteymix** [comment]
I fixed the highlighting so that is starts on the first column excluded (for 80, it's the 81th that is colored).

**Comment by xuhdev** [comment]
Make sense. Thank you!

**Comment by arteymix** [comment]
@xuhdev No problems! :+1:

**Comment by xuhdev** [comment]
Just a follow up: I found this new setup is sometimes distracting (and does not fit people's taste coming from other editors). I'll add an option to choose between the new and old behavior.

**Comment by arteymix** [comment]
Keep at least the `colorcolumn` at `&textwidth+1`, otherwise it's really weird to to have a single character with a different background at the end of the line. That's what most editor do I think.

You could provide an option for coloring until `&columns` (I personally prefer that, but it's up to you).

**Comment by xuhdev** [comment]
That's what's in my mind as well. Just an option to enable and disable coloring all the margin.

**Comment by xuhdev** [comment]
It's done 08bbf5875d987f102bd0ed6868dc4d86acf733a6

**Pull request merged**
