### PR TITLE
Put all non-function code after function definitions

### PR DESCRIPTION
**Pull request by 3onyc**
After updating to the most recent version of editorconfig-vim the following error occurs:

```
Error detected while processing function <SNR>36_FindPythonFiles:
line    3:
E117: Unknown function: <SNR>36_DisableShellSlash
line   18:
E117: Unknown function: <SNR>36_ResetShellSlash
```

These functions were called before they were defined, this pull request moves everything that calls these functions to the bottom of the file, fixing the errors.

### CODE REVIEW

**Comment by sijad** [comment]
I have same problem

**Comment by mtpereira** [comment]
This fixed the issue for me, thank you!

**Comment by pgilad** [comment]
I think the way to go is the put `FindPythonFiles` and `ResetShellSlash` on top so that *they* are defined before usage

**Comment by xuhdev** [comment]
We consider #81 a better fix. Thank you for your contribution!

**Pull request closed without merging**
